title: DRBSD
description: > # this means to ignore newlines until "baseurl:"
# Build settings
markdown: kramdown


logo: "../css/2016_style/img/icon-large.png"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages', '_2022_pages', '_2023_pages', '_2024_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag


